services:
  postgres:
    image: postgres:16-alpine
    container_name: eth-crawler-postgres
    environment:
      POSTGRES_DB: mempool
      POSTGRES_USER: ethcrawler
      POSTGRES_PASSWORD: suyash
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ethcrawler -d mempool"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

